name: CI/CD

on:
  push:
    branches:
      - master
      - develop

jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: "Init repository"
        uses: actions/checkout@v2

      - name: "Setup Node"
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: "Install dependencies"
        run: npm install

      - name: Prettify code
        uses: creyD/prettier_action@v4.0

      - name: Lint code
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/

      - name: "Build app"
        run: npm build

      # - name: "Run tests"
      #   run: npm test -- --no-watch --no-progress

      - name: Deploy staging
        if: github.ref == 'refs/heads/develop'
        run: npm build

      - name: "Install ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: "Install DPL"
        run: gem install dpl

      - name: "Deploy to Heroku"
        if: github.ref == 'refs/heads/master'
        run: dpl --provider=heroku --app=${{secrets.HEROKU_APP}} --api-key=${{secrets.HEROKU_API_KEY}} --skip_cleanup=true